packages:
  - apps/*
  - packages/*

overrides:
  postcss: 8.5.20
  typescript: 5.9.3

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - postcss@8.5.20
